#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]
// The bindings are generated by bindgen; don't lint them.
#![allow(unknown_lints)]
#![allow(unnecessary_transmutes)]
#![allow(clippy::all)]

#[cfg(target_os = "windows")]
include!("./bindings_windows.rs");
#[cfg(target_os = "linux")]
include!("./bindings_linux.rs");
#[cfg(target_os = "macos")]
include!("./bindings_macos.rs");

#[test]
fn test_w3x() {
  use std::ffi::*;
  use std::ptr;

  #[cfg(not(target_os = "windows"))]
  let path = CString::new("../../samples/test_tft.w3x").unwrap();
  #[cfg(target_os = "windows")]
  let path: Vec<_> = {
    "../../samples/test_tft.w3x"
      .as_bytes()
      .iter()
      .cloned()
      .map(u16::from)
      .chain(std::iter::once(0))
      .collect()
  };

  let file = CString::new("war3map.j").unwrap();
  unsafe {
    let mut handle: HANDLE = ptr::null_mut();
    let ok = SFileOpenArchive(
      path.as_ptr(),
      0,
      MPQ_OPEN_NO_LISTFILE | MPQ_OPEN_NO_ATTRIBUTES,
      &mut handle as *mut HANDLE,
    );

    assert!(ok);

    let mut file_handle: HANDLE = ptr::null_mut();
    let ok = SFileOpenFileEx(handle, file.as_ptr(), 0, &mut file_handle as *mut HANDLE);
    assert!(ok);

    let mut size_high: DWORD = 0;
    let size = SFileGetFileSize(file_handle, &mut size_high as *mut DWORD);
    assert!(ok);

    println!("file size = {}", size);

    let mut buf = vec![0u8; size as usize];

    let mut read: DWORD = 0;
    let ok = SFileReadFile(
      file_handle,
      buf.as_mut_ptr().cast(),
      size,
      &mut read as *mut DWORD,
      ptr::null_mut(),
    );
    assert!(ok);

    println!("read size = {}", read);

    assert_eq!(buf, std::fs::read("../../samples/war3map.j").unwrap());

    assert!(SFileCloseFile(file_handle));

    assert!(SFileCloseArchive(handle));
  }
}
